# @package _global_

defaults:
  - _self_
  - dataset: medqa
  - model: llama-2-7b
  - prompt: fewshot-cot
  - system: local

self_consistency: 1
temperature: 0.0

batch_size: 10
num_proc: 128

metrics:
  - "accuracy"
  - "f1"